### ISSUE TITLE
Error running the example....

### ISSUE THREAD

**Issue by super-tomcat** [genotrance/nimscintilla#1]
After installing into Nim 0.20.2 on Windows 64 bit I get the following error after running your example:

Error: execution of an external compiler program 'C:\nim-0.19.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -I"C:/Users/Neil/.nimble/pkgs/nimscintilla-0.2.0/nimscintilla" -I"C:/Users/Neil/.nimble/pkgs/nimscintilla-0.2.0/nimscintilla/scintilla/include" -I"C:/Users/Neil/.nimble/pkgs/nimscintilla-0.2.0/nimscintilla/scintilla/src" -I"C:/Users/Neil/.nimble/pkgs/nimscintilla-0.2.0/nimscintilla/scintilla/lexlib" --std=c++17 -DNDEBUG  -IC:\nim-0.19.2\lib -I"c:\Users\Neil\Documents\Nim Files\wNim" -o C:\Users\Neil\nimcache\scintilla_wrapper_test_d\AutoComplete.cxx.o C:\Users\Neil\.nimble\pkgs\nimscintilla-0.2.0\nimscintilla\scintilla\src\AutoComplete.cxx' failed with exit code: 1

C:\Users\Neil\.nimble\pkgs\nimscintilla-0.2.0\nimscintilla\scintilla\src\AutoComplete.cxx:16:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.

**Comment by genotrance** [comment]
I just looked into this and it is because v6.3.0 of mingw that is linked from nim-lang.org does not have support for string_view. If you can use a newer version of mingw, it should work. I am using 8.1.0.

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/

**Comment by super-tomcat** [comment]
Thanks for quick reply.... I installed.....x86_64-8.1.0-release-posix-seh-rt_v6-rev0

And your example compiled this time, however when running the .exe it displays this:

![Untitled](https://user-images.githubusercontent.com/30247008/62501073-fd324c00-b7e0-11e9-980a-2e36b757d349.jpg)


Have I installed the correct version of mingw?

I'm on windows 10... 64 bit.

The other versions of mingw were these, but i'm not sure of the differences to do with threads etc....

x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0
x86_64-8.1.0-release-win32-seh-rt_v6-rev0
x86_64-8.1.0-release-win32-sjlj-rt_v6-rev0

**Comment by genotrance** [comment]
What does your test look like? Doesn't look like you are using tscinfull.

**Comment by super-tomcat** [comment]
> What does your test look like? Doesn't look like you are using tscinfull.

Am not sure what you mean.... what test? And what is tscinfull?

**Comment by genotrance** [comment]
You are running some test script scintilla_wrapper_test.nim, what does it look like?

**Comment by super-tomcat** [comment]
> You are running some test script scintilla_wrapper_test.nim, what does it look like?

I am compiling the following (your example) using..... nim c -r scintilla_wrapper_test.nim

`
import nimscintilla/[Scintilla, SciLexer]

if Scintilla_RegisterClasses(nil) == 0:
  echo "Failed to init"
  quit(1)

discard Scintilla_ReleaseResources()
`

**Comment by super-tomcat** [comment]
could you find any reason why your example would not compile for me?

**Comment by genotrance** [comment]
Not sure how to proceed here - I'll rather recommend the nimterop based Scintilla wrapper:

https://github.com/genotrance/feud/blob/master/wrappers/scintilla.nim

**Comment by super-tomcat** [comment]
Thanks for any help, but i'm looking at niup now instead....

https://github.com/dariolah/niup
